# Generated by Django 4.1.5 on 2023-01-10 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Наименовние формы"),
                ),
                (
                    "f_name1",
                    models.CharField(max_length=255, verbose_name="Поле email"),
                ),
                (
                    "f_name2",
                    models.CharField(max_length=255, verbose_name="Поле телефон"),
                ),
                ("f_name3", models.CharField(max_length=255, verbose_name="Поле дата")),
                (
                    "f_name4",
                    models.CharField(max_length=255, verbose_name="Поле текст"),
                ),
            ],
            options={
                "verbose_name": "Форма",
                "verbose_name_plural": "Формы",
                "db_table": "forms",
            },
        ),
    ]
