# Generated by Django 4.1.5 on 2023-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_alter_form_f_name1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="f_name1",
            field=models.CharField(
                choices=[
                    ("FR", "Freshman"),
                    ("SO", "Sophomore"),
                    ("JR", "Junior"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                default="FR",
                max_length=255,
                verbose_name="Поле email",
            ),
        ),
    ]
