# Generated by Django 4.1.5 on 2023-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_alter_form_f_name1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="f_name1",
            field=models.CharField(
                default="asd", max_length=255, verbose_name="Поле email"
            ),
        ),
    ]
