# Generated by Django 4.1.5 on 2023-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_alter_form_f_name1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="f_name2",
            field=models.CharField(max_length=255, verbose_name="Поле telephone"),
        ),
        migrations.AlterField(
            model_name="form",
            name="f_name3",
            field=models.CharField(max_length=255, verbose_name="Поле data"),
        ),
        migrations.AlterField(
            model_name="form",
            name="f_name4",
            field=models.CharField(max_length=255, verbose_name="Поле text"),
        ),
    ]
