# Generated by Django 4.1.5 on 2023-01-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_alter_form_f_name2_alter_form_f_name3_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Form",
            new_name="FormTemplate",
        ),
        migrations.AlterModelTable(
            name="formtemplate",
            table="form_template",
        ),
    ]
