# Generated by Django 4.1.5 on 2023-01-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_rename_form_formtemplate_alter_formtemplate_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formtemplate",
            old_name="f_name1",
            new_name="fname1",
        ),
        migrations.RenameField(
            model_name="formtemplate",
            old_name="f_name2",
            new_name="fname2",
        ),
        migrations.RenameField(
            model_name="formtemplate",
            old_name="f_name3",
            new_name="fname3",
        ),
        migrations.RenameField(
            model_name="formtemplate",
            old_name="f_name4",
            new_name="fname4",
        ),
    ]
